name: ezycourse_community
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  fluttertoast: ^8.2.10
  gap: ^3.0.1
  get_it: ^8.0.3
  shared_preferences: ^2.3.5
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  flutter_reaction_button: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
_lints: ^4.0.0

flutter:

  uses-material-design: true

  # ASSETS
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/images/reaction/

  # FONTS
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 900
